### ISSUE TITLE
not gonna lie, nothing works...

### ISSUE THREAD

**Issue by willbarra4** [CRO-THEHACKER/fsociety3#1]
absolute nothing works, and it keeps unistalling itself

**Comment by CRO-THEHACKER** [comment]
Yes I know, I'm working on the new update

**Comment by skluthe** [comment]
@willbarra4 It was moved a month ago and they're porting from python2 to python3 so it's going to be a little bit. @CRO-THEHACKER Thanks for working on this. Really appreciate it!

**Comment by CRO-THEHACKER** [comment]
Okay, everything (should) be working.
