### ISSUE TITLE
Missing uninstall.sh file

### ISSUE THREAD

**Issue by skibum1869** [CRO-THEHACKER/fsociety3#3]
I am having issues running the programs within the framework and would like to uninstall. However, the uninstall file is missing.  See the CLI scripts below. 

`
         python3 build - version: 1.3 - Last update: 1/4/20                                                    
            
             }---{Made by CRO-THEHACKER & Manisso}---{
        }---{https://github.com/CRO-THEHACKER/fsociety3}---{
            
        |---------------------[Main Options]---------------|
        |    1) Install   FSociety3                        |
        |    2) Update    FSociety3                        |
        |    3) Uninstall FSociety3                        |
        |------------------------[MISC.]-------------------|
        |    4) Need help? Do this option...               |
        |--------------------------------------------------|

FSOCIETY$: 3
bash: uninstall.sh: No such file or directory
FSOCIETY3: STAT_CODE=DONE
`

**Comment by CRO-THEHACKER** [comment]
Thank you for addressing this issue. I'll get on it!
